<a href="https://colab.research.google.com/github/padmasri2005/DataScience-Tasks/blob/main/Data_Cleaning_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
# importing necessary libraries
import pandas as pd
import numpy as np

In [95]:
# loading the data
df = pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/medical_students_dataset.csv")

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Student ID      180000 non-null  float64
 1   Age             180000 non-null  float64
 2   Gender          180000 non-null  object
 3   Height          180000 non-null  float64
 4   Weight          180000 non-null  float64
 5   Blood Type      180000 non-null  object
 6   BMI             180000 non-null  float64
 7   Temperature     180000 non-null  float64
 8   Heart Rate      180000 non-null  float64
 9   Blood Pressure  180000 non-null  float64
 10  Cholesterol     180000 non-null  float64
 11  Diabetes        180000 non-null  object
 12  Smoking         180000 non-null  object
dtypes: float64(9), object(4)
memory usage: 19.8+ MB

In [97]:
df.head()

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.0,Female,161.777924,72.354947,O,27.645835,NaN,95.0,109.0,203.0,No,NaN
1,2.0,NaN,Male,152.069157,47.630941,B,NaN,98.714977,93.0,104.0,163.0,No,No
2,3.0,32.0,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,NaN,30.0,Male,182.112867,63.332207,B,19.096042,98.839605,99.0,112.0,141.0,No,Yes
4,5.0,23.0,Female,NaN,46.234173,O,NaN,98.480008,95.0,NaN,231.0,No,No

In [98]:
df.isnull()
df.isnull().sum()

Student ID        20000
Age               20000
Gender            20000
Height            20000
Weight            20000
Blood Type        20000
BMI               20000
Temperature       20000
Heart Rate        20000
Blood Pressure    20000
Cholesterol       20000
Diabetes          20000
Smoking           20000
dtype: int64

In [99]:
df.drop_duplicates(inplace = True)

In [100]:
# handling null in age
df['Age'].unique()
# print("Mean : ",df['Age'].mean())
# print("Mode : ",df['Age'].mode())
# print("Median : ",df['Age'].median())
df['Age'] = df['Age'].fillna(df['Age'].median()) # as median and mean have the same value -- 26.0
df['Age'] = df['Age'].astype(int)
df['Age'].isnull().sum()

np.int64(0)

In [101]:
# handling null in Height
df['Height'].unique()
sorted(df['Age'].unique()) # no ouliers
print("Mean : ",df['Height'].mean())
# # print("Mode : ",df['Height'].mode())
print("Median : ",df['Height'].median())
df['Height'] = df['Height'].fillna(df['Height'].mean()) # as median and mean have the same value -- 174.9

df['Height'].isnull().sum()

Mean :  174.95836280064614
Median :  174.92034497111456

np.int64(0)

In [102]:
# handling null in Weight
df['Weight'].unique()
print("Mean : ",df['Weight'].mean())
# print("Mode : ",df['Weight'].mode())
print("Median : ",df['Weight'].median())
df['Weight'] = df['Weight'].fillna(df['Weight'].median()) # as median and mean have the same value -- 6

df['Weight'].isnull().sum()

Mean :  69.98082740762183
Median :  69.99507837940445

np.int64(0)

In [103]:
# handling null in BMI
df['BMI'].unique()
print("Mean : ",df['BMI'].mean())
# print("Mode : ",df['BMI'].mode())
print("Median : ",df['BMI'].median())
df['BMI'] = df['BMI'].fillna(df['BMI'].mean()) # as median and mean have the same value

df['BMI'].isnull().sum()

Mean :  23.33898224304186
Median :  22.670745757247737

np.int64(0)

In [104]:
# handling null in Temperature
df['Temperature'].unique()
print("Mean : ",df['Temperature'].mean())
# print("Mode : ",df['Temperature'].mode())
print("Median : ",df['Temperature'].median())
df['Temperature'] = df['Temperature'].fillna(df['Temperature'].mean()) # as median and mean have the same value
df['Temperature'].isnull().sum()

Mean :  98.60111656260159
Median :  98.599527319438

np.int64(0)

In [105]:
# handling null in Heart Rate
df['Heart Rate'].unique()
print("Mean : ",df['Heart Rate'].mean())
print("Median : ",df['Heart Rate'].median())
df['Heart Rate'] = df['Heart Rate'].fillna(df['Heart Rate'].median()) # as mean giving decimals and no unique is float-- better to go with median and convert to int
df['Heart Rate'] = df['Heart Rate'].astype(int)
df['Heart Rate'].isnull().sum()

Mean :  79.50881689503807
Median :  80.0

np.int64(0)

In [106]:
# handling null in Blood Pressure
df['Blood Pressure'].unique()
print("Mean : ",df['Blood Pressure'].mean())
# print("Mode : ",df['Blood Pressure'].mode())
print("Median : ",df['Blood Pressure'].median())
df['Blood Pressure'] = df['Blood Pressure'].fillna(df['Blood Pressure'].median()) # as mean giving decimals and no unique is float-- better to go with median and convert to int
df['Blood Pressure'] = df['Blood Pressure'].astype(int)
df['Blood Pressure'].isnull().sum()

Mean :  114.56476134149736
Median :  115.0

np.int64(0)

In [107]:
# handling null in Cholesterol
df['Cholesterol'].unique()
print("Mean : ",df['Cholesterol'].mean())
print("Median : ",df['Cholesterol'].median())
df['Cholesterol'] = df['Cholesterol'].fillna(df['Cholesterol'].median()) # as mean giving decimals and no unique is float-- better to go with median and convert to int
df['Cholesterol'] = df['Cholesterol'].astype(int)
df['Cholesterol'].isnull().sum()

Mean :  184.49976516702134
Median :  184.0

np.int64(0)

In [108]:
# handling null in Diabetes
df['Diabetes'].unique()
print("Mode : ",df['Diabetes'].mode())

df['Diabetes'] = df['Diabetes'].fillna(df['Diabetes'].mode()[0]) # 1st value of mode

df['Diabetes'].isnull().sum()

Mode :  0    No
Name: Diabetes, dtype: object

np.int64(0)

In [109]:
# handling null in Smoking
df['Smoking'].unique()
print("Mode : ",df['Smoking'].mode())

df['Smoking'] = df['Smoking'].fillna(df['Smoking'].mode()[0]) # 1st value of mode

df['Smoking'].isnull().sum()

Mode :  0    No
Name: Smoking, dtype: object

np.int64(0)

In [110]:
# handling null in Blood Type
df['Blood Type'].unique()
df['Blood Type'] = df['Blood Type'].fillna(df['Blood Type'].mode()[0])
df['Blood Type'].unique()

array(['O', 'B', 'A', 'AB'], dtype=object)

In [111]:
# handling null in Gender
df['Gender'].unique()
# print("Mode : ",df['Gender'].mode())

df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0]) # 1st value of mode

df['Gender'].isnull().sum()

np.int64(0)

In [112]:
# handling StudentID
df.dropna(inplace = True)

In [113]:
df.isnull().sum()

Student ID        0
Age               0
Gender            0
Height            0
Weight            0
Blood Type        0
BMI               0
Temperature       0
Heart Rate        0
Blood Pressure    0
Cholesterol       0
Diabetes          0
Smoking           0
dtype: int64